#!/usr/bin/env bash
# Depot Air — Automated Installer (Ubuntu 22.04+)
#
# Install dari scratch di server baru. Cover langkah 1-7 di INSTALASI.md
# (sampai service jalan). Step manual (Cloudflare tunnel, Apps Script,
# pengaturan) tetap perlu admin lakukan via UI setelah ini.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/jafarains-cmd/depotgnr/main/scripts/install.sh | sudo bash
#   ATAU clone dulu lalu:
#   sudo bash scripts/install.sh

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}▸${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*" >&2; }

# Cek root
if [[ $EUID -ne 0 ]]; then
  err "Script ini harus dijalankan sebagai root (atau via sudo)."
  exit 1
fi

# Cek Ubuntu
if ! grep -qi "ubuntu" /etc/os-release; then
  warn "Bukan Ubuntu — script ini dites di Ubuntu 22.04. Lanjutkan? (y/N)"
  read -r ans
  [[ "$ans" =~ ^[Yy]$ ]] || exit 0
fi

APP_DIR="/opt/depot-air"
APP_USER="depot"
SERVICE="depot-air"
REPO="https://github.com/jafarains-cmd/depotgnr.git"
PORT="${PORT:-3000}"

# ==============================================================
# 1. Install dependencies
# ==============================================================
log "Step 1/7: Update apt & install Node.js 20 + build tools..."
apt update -qq
apt upgrade -y -qq

if ! command -v node &>/dev/null || [[ $(node -v | sed 's/v//' | cut -d. -f1) -lt 20 ]]; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - > /dev/null 2>&1
  apt install -y nodejs
fi

apt install -y build-essential python3 git curl ca-certificates gnupg sqlite3 > /dev/null 2>&1

log "  Node.js: $(node -v) · npm: $(npm -v)"

# ==============================================================
# 2. Bikin user depot
# ==============================================================
log "Step 2/7: Bikin user '$APP_USER'..."
if id "$APP_USER" &>/dev/null; then
  log "  User $APP_USER sudah ada — skip."
else
  adduser --system --group --shell /bin/bash --home "$APP_DIR" "$APP_USER"
fi

# ==============================================================
# 3. Clone repo
# ==============================================================
log "Step 3/7: Clone repo ke $APP_DIR..."
if [[ -d "$APP_DIR/.git" ]]; then
  log "  Repo sudah ada — skip clone. Pull update."
  cd "$APP_DIR"
  sudo -u "$APP_USER" -H git pull --ff-only
else
  # Hapus folder home auto-created adduser supaya git clone bersih
  rm -rf "$APP_DIR"
  git clone "$REPO" "$APP_DIR"
  chown -R "$APP_USER:$APP_USER" "$APP_DIR"
fi

# ==============================================================
# 4. npm install + build
# ==============================================================
log "Step 4/7: npm ci + build (1-2 menit)..."
sudo -u "$APP_USER" -H bash -lc "cd $APP_DIR && npm ci"
sudo -u "$APP_USER" -H bash -lc "cd $APP_DIR && npm run build"

# ==============================================================
# 5. Setup .env.local
# ==============================================================
log "Step 5/7: Setup .env.local..."
ENV_FILE="$APP_DIR/.env.local"
if [[ -f "$ENV_FILE" ]]; then
  log "  $ENV_FILE sudah ada — skip generate."
else
  AUTH_SECRET=$(openssl rand -hex 32)
  SHEET_SECRET=$(openssl rand -hex 16)
  cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh
DATABASE_URL=$APP_DIR/data/depot.db
BETTER_AUTH_URL=http://localhost:$PORT
BETTER_AUTH_SECRET=$AUTH_SECRET

# Telegram (opsional — set lewat /admin/pengaturan)
TELEGRAM_BOT_TOKEN=
ADMIN_TELEGRAM_CHAT_ID=

# WhatsApp Fonnte (opsional)
WHATSAPP_PROVIDER=fonnte
WHATSAPP_API_URL=https://api.fonnte.com/send
WHATSAPP_API_KEY=

# Sheet sync (untuk spreadsheet cadangan saat aplikasi down)
SHEET_SYNC_SECRET=$SHEET_SECRET

NODE_ENV=production
PORT=$PORT
EOF
  chmod 600 "$ENV_FILE"
  chown "$APP_USER:$APP_USER" "$ENV_FILE"
  warn "  ⚠ Ganti BETTER_AUTH_URL ke domain Anda setelah setup Cloudflare tunnel"
fi

# ==============================================================
# 6. Database setup
# ==============================================================
log "Step 6/7: Setup database & migration..."
sudo -u "$APP_USER" -H bash -lc "cd $APP_DIR && mkdir -p data && npm run db:migrate"
sudo -u "$APP_USER" -H bash -lc "cd $APP_DIR && npm run db:create-admin" || warn "  Admin mungkin sudah ada, skip."

# ==============================================================
# 7. systemd service
# ==============================================================
log "Step 7/7: Bikin systemd service..."
cat > /etc/systemd/system/$SERVICE.service <<EOF
[Unit]
Description=Depot Air Minum App
After=network.target

[Service]
Type=simple
User=$APP_USER
Group=$APP_USER
WorkingDirectory=$APP_DIR
ExecStart=/usr/bin/npm start
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
LimitNOFILE=4096
MemoryMax=1500M

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable $SERVICE > /dev/null 2>&1
systemctl restart $SERVICE
sleep 3

if systemctl is-active --quiet $SERVICE; then
  log "✓ Service running."
else
  err "Service gagal start. Cek: journalctl -u $SERVICE -n 50"
  exit 1
fi

# Verifikasi HTTP
sleep 2
if curl -sf "http://localhost:$PORT/api/health" > /dev/null; then
  log "✓ Health check OK: http://localhost:$PORT/api/health"
else
  warn "Service running tapi /api/health tidak respond — cek log"
fi

# Setup symlink depot-update
ln -sf "$APP_DIR/scripts/update.sh" /usr/local/bin/depot-update
chmod +x "$APP_DIR/scripts/update.sh"

# ==============================================================
# Selesai
# ==============================================================
echo ""
echo "================================================"
echo -e "${GREEN}✓ INSTALASI SELESAI${NC}"
echo "================================================"
echo ""
echo "Aplikasi running di: http://localhost:$PORT"
echo "Admin default:       admin@depot.local / admin123"
echo ""
echo "Langkah berikutnya (manual, lihat docs/INSTALASI.md):"
echo "  8. Setup Cloudflare Tunnel"
echo "  9. Setup Apps Script (upload + backup)"
echo " 10. Setup pengaturan aplikasi via /admin/pengaturan"
echo " 11. Setup cron backup harian"
echo ""
echo "Update aplikasi nanti tinggal: ${YELLOW}sudo depot-update${NC}"
echo ""
